name: endofm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - cudatoolkit=11.3
  - numpy
  - pip
  - pip:
    - torch==1.11.0+cu113
    - torchvision==0.12.0+cu113
    - --extra-index-url https://download.pytorch.org/whl/cu113
    - absl-py==1.4.0
    - addict==2.4.0
    - av==10.0.0
    - charset-normalizer==3.1.0
    - click==8.1.3
    - colorama==0.4.6
    - contextlib2==21.6.0
    - cycler==0.11.0
    - cython==0.29.35
    - einops==0.6.1
    - fonttools==4.38.0
    - fvcore==0.1.5.post20221221
    - h5py==3.8.0
    - idna==3.4
    - importlib-metadata==6.6.0
    - iopath==0.1.10
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - kornia==0.5.8
    - markdown==3.4.3
    - markdown-it-py==2.2.0
    - matplotlib==3.5.3
    - mdurl==0.1.2
    - medpy==0.4.0
    - ml-collections==0.1.1
    - mmcv==1.6.0
    - model-index==0.1.11
    - ninja==1.11.1
    - opencv-python==3.4.3.18
    - openmim==0.3.7
    - ordered-set==4.1.0
    - packaging==23.1
    - pandas==1.3.5
    - pillow==6.2.2
    - portalocker==2.7.0
    - protobuf==3.20.3
    - pygments==2.15.1
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pyyaml==6.0
    - requests==2.31.0
    - rich==13.4.1
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - simpleitk==2.2.1
    - simplejson==3.19.1
    - tabulate==0.9.0
    - tensorboardx==2.6
    - termcolor==2.3.0
    - thop==0.1.1-2209072238
    - threadpoolctl==3.1.0
    - timm==0.4.12
    - tomli==2.0.1
    - tqdm==4.65.0
    - urllib3==2.0.2
    - yacs==0.1.8
    - yapf==0.33.0
    - zipp==3.15.0